version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: agile_academusoft_v2_backend_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

#  nodejs:
#    build:
#      context: .
#      dockerfile: compose/local/nodejs/Dockerfile
#    image: agile_academusoft_v2_front_local_nodejs
#    container_name: nodejs
#    ports:
#      - 5000:5000
#    depends_on:
#      - django
#    command: /start

  postgres:
    build:
      context: .
      dockerfile: compose/production/postgres/Dockerfile
    image: agile_academusoft_v2_backend_local_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - .envs/.local/.postgres

  redis:
    image: redis:6
    container_name: redis
