version: '3'

volumes:
  auth_local_postgres_data: {}
  auth_local_postgres_data_backups: {}

services:
  auth_ms:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: auth_local_django
    container_name: auth_ms
    depends_on:
      - auth_db
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  auth2_ms:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: auth_local_django
    container_name: auth2_ms
    depends_on:
      - auth_db
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - "8005:8000"
    command: /start

  auth_db:
    build:
      context: .
      dockerfile: compose/production/postgres/Dockerfile
    image: auth_local_postgres
    container_name: auth_db
    volumes:
      - auth_local_postgres_data:/var/lib/postgresql/data:Z
      - auth_local_postgres_data_backups:/backups:z
    env_file:
      - .envs/.local/.postgres
    ports:
      - "5430:5432"

  auth_redis:
    image: redis:6
    container_name: auth_redis

  aaw-ldap:
    image: osixia/openldap:1.5.0 # previous 1.1.8
    container_name: aaw_ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "mdb" # fixed for mac m1 arm64 https://github.com/osixia/docker-openldap/issues/451
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.unal.edu.co"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap_client
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "aaw-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - aaw-ldap
