# Generated by Django 3.1.13 on 2021-10-03 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211001_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Record Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Record Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Record Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Record Identifier', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Record Identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20)),
                ('start_time', models.PositiveSmallIntegerField()),
                ('end_time', models.PositiveSmallIntegerField()),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='courses.coursegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
